package com.kamiwa.kemeticcalendar.core

import com.kamiwa.kemeticcalendar.R

data class KemeticMonth(
    val startDay: Int,
    val startMonth: Int,
    val endDay: Int,
    val endMonth: Int,
    val key: Int
)

data class KemeticHoliday(
    val month: Int,
    val day: Int,
    val key: Int
)

data class LunarHoliday(
    val phase: String,
    val delta: Int,
    val key: Int
)

val KEMETIC_MONTHS = listOf(
    KemeticMonth(18, 7, 16, 8, R.string.kemetic_month_dzehutet),
    KemeticMonth(17, 8, 15, 9, R.string.kemetic_month_paen_opet),
    KemeticMonth(16, 9, 15, 10, R.string.kemetic_month_hat_hor),
    KemeticMonth(16, 10, 14, 11, R.string.kemetic_month_ka_her_ka),
    KemeticMonth(15, 11, 14, 12, R.string.kemetic_month_taibet),
    KemeticMonth(15, 12, 13, 1, R.string.kemetic_month_makhir),
    KemeticMonth(14, 1, 12, 2, R.string.kemetic_month_paen_amunhotepu),
    KemeticMonth(13, 2, 14, 3, R.string.kemetic_month_paen_rennutet),
    KemeticMonth(15, 3, 13, 4, R.string.kemetic_month_pa_khonsu),
    KemeticMonth(14, 4, 13, 5, R.string.kemetic_month_paen_inet),
    KemeticMonth(14, 5, 12, 6, R.string.kemetic_month_apip),
    KemeticMonth(13, 6, 12, 7, R.string.kemetic_month_mosu_ra),
    KemeticMonth(13, 7, 17, 7, R.string.kemetic_month_heru_diu)
)

val KEMETIC_HOLIDAYS = listOf(
    KemeticHoliday(0, 1, R.string.kemetic_holiday_upet_ronpet),
    KemeticHoliday(0, 2, R.string.kemetic_holiday_ihi_comes_forward),
    KemeticHoliday(0, 9, R.string.kemetic_holiday_hathor_comes_forward),
    KemeticHoliday(0, 10, R.string.kemetic_holiday_festival_of_tefnut_in_esna),
    KemeticHoliday(0, 17, R.string.kemetic_holiday_festival_of_uagi),
    KemeticHoliday(0, 18, R.string.kemetic_holiday_festival_of_uagi),
    KemeticHoliday(0, 19, R.string.kemetic_holiday_festival_of_djehutet),
    KemeticHoliday(0, 20, R.string.kemetic_holiday_cleansing_of_ra),
    KemeticHoliday(0, 21, R.string.kemetic_holiday_festival_of_tekhi),
    KemeticHoliday(0, 22, R.string.kemetic_holiday_osiris_comes_forward_festival_of_anubis_in_junit),
    KemeticHoliday(0, 30, R.string.kemetic_holiday_festival_of_osiris_and_his_ennead_in_abydos),

    KemeticHoliday(1, 2, R.string.kemetic_holiday_elder_horus_visits_neit),
    KemeticHoliday(1, 3, R.string.kemetic_holiday_festival_of_sobek),
    KemeticHoliday(1, 6, R.string.kemetic_holiday_festival_of_isis_great),
    KemeticHoliday(1, 9, R.string.kemetic_holiday_sailing_of_horus_behdet),
    KemeticHoliday(1, 10, R.string.kemetic_holiday_procession_of_bastet),
    KemeticHoliday(1, 16, R.string.kemetic_holiday_festival_of_unnofer_neit),
    KemeticHoliday(1, 17, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 18, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 19, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 20, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 21, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 22, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 23, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 24, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 25, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 26, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 27, R.string.kemetic_holiday_dressing_of_anubis_festival_of_montu),
    KemeticHoliday(1, 18, R.string.kemetic_holiday_festival_of_khnum_and_anuket),
    KemeticHoliday(1, 18, R.string.kemetic_holiday_festival_of_opet),
    KemeticHoliday(1, 19, R.string.kemetic_holiday_festival_of_opet),
    KemeticHoliday(1, 20, R.string.kemetic_holiday_festival_of_opet),
    KemeticHoliday(1, 21, R.string.kemetic_holiday_festival_of_opet),
    KemeticHoliday(1, 22, R.string.kemetic_holiday_festival_of_opet),
    KemeticHoliday(1, 23, R.string.kemetic_holiday_festival_of_opet),
    KemeticHoliday(1, 24, R.string.kemetic_holiday_festival_of_opet),
    KemeticHoliday(1, 25, R.string.kemetic_holiday_festival_of_opet),
    KemeticHoliday(1, 24, R.string.kemetic_holiday_carrying_sand_for_anubis),
    KemeticHoliday(1, 28, R.string.kemetic_holiday_festival_of_satit_and_anuket_in_elephantine),

    KemeticHoliday(2, 1, R.string.kemetic_holiday_festival_of_sakhmet_in_esna),
    KemeticHoliday(2, 3, R.string.kemetic_holiday_first_festival_of_uedjet),
    KemeticHoliday(2, 8, R.string.kemetic_holiday_isis_comes_forward_in_joy),
    KemeticHoliday(2, 9, R.string.kemetic_holiday_festival_of_amun),
    KemeticHoliday(2, 10, R.string.kemetic_holiday_festival_of_neit_and_tutu_in_esna),
    KemeticHoliday(2, 17, R.string.kemetic_holiday_isis_and_nephthys_mourn_osiris_festival_of_amun_after_opet),
    KemeticHoliday(2, 21, R.string.kemetic_holiday_festival_of_shu_son_of_ra),
    KemeticHoliday(2, 22, R.string.kemetic_holiday_maat_raised_to_ra),
    KemeticHoliday(2, 24, R.string.kemetic_holiday_isis_comes_forward_nephthys_in_joy),
    KemeticHoliday(2, 28, R.string.kemetic_holiday_festival_of_hathor_residing_in_ombos),
    KemeticHoliday(2, 29, R.string.kemetic_holiday_festival_of_horus_behdet),
    KemeticHoliday(2, 30, R.string.kemetic_holiday_festival_of_horus_behdet),
    KemeticHoliday(2, 30, R.string.kemetic_holiday_sailing_of_hathor_revealing_female_breasts),

    KemeticHoliday(3, 1, R.string.kemetic_holiday_festival_of_horus_behdet),
    KemeticHoliday(3, 1, R.string.kemetic_holiday_ra_joy_festival_of_hathor_offerings_to_amun_ra),
    KemeticHoliday(3, 4, R.string.kemetic_holiday_perform_rites_for_sobek),
    KemeticHoliday(3, 5, R.string.kemetic_holiday_revelation_of_neit),
    KemeticHoliday(3, 11, R.string.kemetic_holiday_festival_of_osiris_in_abydos),
    KemeticHoliday(3, 15, R.string.kemetic_holiday_festival_of_sakhmet_and_bastet),
    KemeticHoliday(3, 18, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 19, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 20, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 21, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 22, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 23, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 24, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 25, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 26, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 27, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 28, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 29, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 30, R.string.kemetic_holiday_mysteries_of_osiris),
    KemeticHoliday(3, 20, R.string.kemetic_holiday_cleansing_of_ennead),
    KemeticHoliday(3, 22, R.string.kemetic_holiday_digging_the_earth),
    KemeticHoliday(3, 25, R.string.kemetic_holiday_nocherit_day),
    KemeticHoliday(3, 26, R.string.kemetic_holiday_neit_and_hathor_unite_with_solar_disk_festival_of_sokar),
    KemeticHoliday(3, 27, R.string.kemetic_holiday_neit_and_hathor_unite_with_solar_disk_festival_of_sokar),
    KemeticHoliday(3, 28, R.string.kemetic_holiday_carrying_forward_stone_of_benben),
    KemeticHoliday(3, 30, R.string.kemetic_holiday_lifting_of_djed),

    KemeticHoliday(4, 1, R.string.kemetic_holiday_coronation_of_holy_falcon_hab_sed_festival_of_neheb_kau),
    KemeticHoliday(4, 2, R.string.kemetic_holiday_second_festival_of_uedjet),
    KemeticHoliday(4, 3, R.string.kemetic_holiday_drinking_festival_in_edfu),
    KemeticHoliday(4, 16, R.string.kemetic_holiday_shu_comes_forward),
    KemeticHoliday(4, 18, R.string.kemetic_holiday_festival_of_neit_on_her_lake_heka_holy_day_in_ro_setau),
    KemeticHoliday(4, 19, R.string.kemetic_holiday_festival_of_neit_on_her_lake_heka_holy_day_in_ro_setau),
    KemeticHoliday(4, 20, R.string.kemetic_holiday_festival_of_neit_on_her_lake_heka_holy_day_in_ro_setau),
    KemeticHoliday(4, 21, R.string.kemetic_holiday_festival_of_neit_on_her_lake_heka_holy_day_in_ro_setau),
    KemeticHoliday(4, 19, R.string.kemetic_holiday_sailing_of_bast_uedjet_hathor_in_junit),
    KemeticHoliday(4, 20, R.string.kemetic_holiday_sailing_of_bast_uedjet_hathor_in_junit),
    KemeticHoliday(4, 21, R.string.kemetic_holiday_sailing_of_bast_uedjet_hathor_in_junit),
    KemeticHoliday(4, 25, R.string.kemetic_holiday_establishment_of_heavenly_cow),
    KemeticHoliday(4, 28, R.string.kemetic_holiday_djehuti_takes_oath_in_khemnu),
    KemeticHoliday(4, 30, R.string.kemetic_holiday_sailing_of_mut),

    KemeticHoliday(5, 1, R.string.kemetic_holiday_ptah_lifts_sky_sailing_of_anubis_in_dzeme),
    KemeticHoliday(5, 6, R.string.kemetic_holiday_djed_raised_for_osiris_in_abydos_festival_of_shu_sakhmet),
    KemeticHoliday(5, 8, R.string.kemetic_holiday_opening_of_neit_house_in_sais),
    KemeticHoliday(5, 9, R.string.kemetic_holiday_amun_lifts_heavens_festival_of_great_burning),
    KemeticHoliday(5, 10, R.string.kemetic_holiday_ra_lifts_maat),
    KemeticHoliday(5, 11, R.string.kemetic_holiday_sobek_comes_forward_festival_of_neit),
    KemeticHoliday(5, 16, R.string.kemetic_holiday_isis_rises),
    KemeticHoliday(5, 17, R.string.kemetic_holiday_festival_of_mina_lord_of_sais_neit_anubis),
    KemeticHoliday(5, 21, R.string.kemetic_holiday_festival_of_victory_of_horus_third_festival_of_uedjet),
    KemeticHoliday(5, 22, R.string.kemetic_holiday_festival_of_victory_of_horus_third_festival_of_uedjet),
    KemeticHoliday(5, 23, R.string.kemetic_holiday_festival_of_victory_of_horus_third_festival_of_uedjet),
    KemeticHoliday(5, 24, R.string.kemetic_holiday_festival_of_victory_of_horus_third_festival_of_uedjet),
    KemeticHoliday(5, 25, R.string.kemetic_holiday_festival_of_victory_of_horus_third_festival_of_uedjet),
    KemeticHoliday(5, 26, R.string.kemetic_holiday_min_comes_forward_to_koptos),
    KemeticHoliday(5, 27, R.string.kemetic_holiday_festival_of_sokar_in_ro_setau_unnofer),
    KemeticHoliday(5, 28, R.string.kemetic_holiday_festival_of_sokar_in_ro_setau_unnofer),
    KemeticHoliday(5, 30, R.string.kemetic_holiday_festival_of_filling_of_holy_eye),

    KemeticHoliday(6, 1, R.string.kemetic_holiday_festival_of_neit_uedjet_ptah_lifts_sky_in_esna),
    KemeticHoliday(6, 5, R.string.kemetic_holiday_neit_from_sais_comes_forward_at_night),
    KemeticHoliday(6, 6, R.string.kemetic_holiday_anubis_comes_forward_with_worshippers),
    KemeticHoliday(6, 8, R.string.kemetic_holiday_gods_create_path_for_khnum),
    KemeticHoliday(6, 9, R.string.kemetic_holiday_fourth_festival_of_uedjet),
    KemeticHoliday(6, 13, R.string.kemetic_holiday_djehuti_comes_forward),
    KemeticHoliday(6, 18, R.string.kemetic_holiday_festival_of_nut),
    KemeticHoliday(6, 23, R.string.kemetic_holiday_festival_of_horus_in_kem_ur),
    KemeticHoliday(6, 28, R.string.kemetic_holiday_festival_of_osiris_in_abydos_lifting_of_trt_tree),
    KemeticHoliday(6, 29, R.string.kemetic_holiday_amun_enters_heavens),

    KemeticHoliday(7, 1, R.string.kemetic_holiday_uedjet_enters_heavens_festival_of_neit_khnum_ra_and_his_eye),
    KemeticHoliday(7, 2, R.string.kemetic_holiday_geb_comes_forward_to_visit_anubis),
    KemeticHoliday(7, 4, R.string.kemetic_holiday_min_comes_forward_to_his_festival_tent_festivals_of_pakhet_horus_chewing_onion_for_bastet),
    KemeticHoliday(7, 5, R.string.kemetic_holiday_festival_of_bastet_in_her_bark),
    KemeticHoliday(7, 8, R.string.kemetic_holiday_completion_of_eye_udjat_of_horus),
    KemeticHoliday(7, 11, R.string.kemetic_holiday_exit_of_neit_and_child_of_heka_from_sais),
    KemeticHoliday(7, 16, R.string.kemetic_holiday_khopri_comes_forward),
    KemeticHoliday(7, 19, R.string.kemetic_holiday_ra_sails_from_junu),
    KemeticHoliday(7, 20, R.string.kemetic_holiday_appearance_of_sobek_in_ombos),
    KemeticHoliday(7, 28, R.string.kemetic_holiday_festival_of_horus_of_sepa_son_of_sakhmet),

    KemeticHoliday(8, 1, R.string.kemetic_holiday_horus_son_of_isis_horus_sema_taui_rennutet_hathor_jusaas_amun_min_comes_forward),
    KemeticHoliday(8, 4, R.string.kemetic_holiday_chewing_onion_for_bastet_in_dzeme),
    KemeticHoliday(8, 10, R.string.kemetic_holiday_dressing_of_anubis_dua_anubis),
    KemeticHoliday(8, 11, R.string.kemetic_holiday_min_comes_forward_in_dzeme_hathor_gives_birth),
    KemeticHoliday(8, 15, R.string.kemetic_holiday_amun_min_appears_in_esna),
    KemeticHoliday(8, 19, R.string.kemetic_holiday_khonsu_comes_forward),
    KemeticHoliday(8, 21, R.string.kemetic_holiday_birth_of_horus_son_of_isis_in_edfu),
    KemeticHoliday(8, 30, R.string.kemetic_holiday_festival_of_mina_khonsu_and_rennutet),

    KemeticHoliday(9, 1, R.string.kemetic_holiday_khnum_and_neit_come_forward_in_esna_festival_of_hathor_eye_of_ra_in_bubastis),
    KemeticHoliday(9, 1, R.string.kemetic_holiday_beautiful_valley_festival),
    KemeticHoliday(9, 2, R.string.kemetic_holiday_beautiful_valley_festival),
    KemeticHoliday(9, 16, R.string.kemetic_holiday_festival_of_bastet_cleansing_of_sakhmet_in_esna),
    KemeticHoliday(9, 26, R.string.kemetic_holiday_revealing_faces_in_neit_house_in_esna),
    KemeticHoliday(9, 30, R.string.kemetic_holiday_shu_comes_forward_to_return_tefnut_appearance_of_dzehuti_satisfying_sakhmet_in_esna),

    KemeticHoliday(10, 1, R.string.kemetic_holiday_festival_of_ipet_hemet_tawret),
    KemeticHoliday(10, 7, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 8, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 9, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 10, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 11, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 12, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 13, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 14, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 15, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 16, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 17, R.string.kemetic_holiday_festival_of_beautiful_union),
    KemeticHoliday(10, 13, R.string.kemetic_holiday_festival_of_neit_who_saved_ra),
    KemeticHoliday(10, 14, R.string.kemetic_holiday_eating_cucumbers_by_eye_of_horus_chewing_cucumbers_for_sakhmet),
    KemeticHoliday(10, 19, R.string.kemetic_holiday_revelation_of_khnum_grasping_staff),
    KemeticHoliday(10, 20, R.string.kemetic_holiday_revelation_of_khnum_grasping_staff),
    KemeticHoliday(10, 29, R.string.kemetic_holiday_festival_of_mut_in_iszeru),
    KemeticHoliday(10, 30, R.string.kemetic_holiday_festival_of_apip),

    KemeticHoliday(11, 1, R.string.kemetic_holiday_festival_of_unnofer_khnum_ra_hathor_in_junit_and_her_ennead_comes_forward),
    KemeticHoliday(11, 2, R.string.kemetic_holiday_isis_shining_exit_of_wonderful_isis),
    KemeticHoliday(11, 3, R.string.kemetic_holiday_her_highness_hathor_comes_forward_to_ra_in_junu),
    KemeticHoliday(11, 4, R.string.kemetic_holiday_festival_of_set),
    KemeticHoliday(11, 5, R.string.kemetic_holiday_min_in_akhmim),
    KemeticHoliday(11, 22, R.string.kemetic_holiday_festival_of_anubis_on_his_mountain),
    KemeticHoliday(11, 27, R.string.kemetic_holiday_hathor_comes_forward),
    KemeticHoliday(11, 28, R.string.kemetic_holiday_festival_of_mina),
    KemeticHoliday(11, 29, R.string.kemetic_holiday_festival_of_sokar_in_house_of_ptah),
    KemeticHoliday(11, 30, R.string.kemetic_holiday_day_of_mosit_last_day_of_year),

    KemeticHoliday(12, 1, R.string.kemetic_holiday_birth_of_osiris),
    KemeticHoliday(12, 2, R.string.kemetic_holiday_birth_of_horus),
    KemeticHoliday(12, 3, R.string.kemetic_holiday_birth_of_set),
    KemeticHoliday(12, 4, R.string.kemetic_holiday_birth_of_isis),
    KemeticHoliday(12, 5, R.string.kemetic_holiday_birth_of_nephthys)
)

val LUNAR_HOLIDAYS = listOf(
    LunarHoliday("new_moon", 0, R.string.lunar_holiday_new_moon_pesdzentiu),
    LunarHoliday("new_moon", 1, R.string.lunar_holiday_new_moon_abed),
    LunarHoliday("new_moon", 5, R.string.lunar_holiday_new_moon_senut),
    LunarHoliday("new_moon", 6, R.string.lunar_holiday_new_moon_denit_first_quarter),
    LunarHoliday("last_quarter", 0, R.string.lunar_holiday_last_quarter_denit_third_quarter),
    LunarHoliday("full_moon", 0, R.string.lunar_holiday_full_moon_medzh_diunit),
    LunarHoliday("new_moon", -1, R.string.lunar_holiday_new_moon_poret_min)
)